/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realworld;

import Design.Colors;
import GUIs.MainScreen;
import com.pearson.pdn.learningstudio.oauth.OAuth2PasswordService;
import com.pearson.pdn.learningstudio.oauth.OAuthServiceFactory;
import com.pearson.pdn.learningstudio.oauth.config.OAuthConfig;
import com.pearson.pdn.learningstudio.oauth.request.OAuth2Request;
import java.awt.Color;
import java.net.URL;
import java.util.Map;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXFrame;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.SwingXUtilities;
import pearson.AuthenticationData;

/**
 *
 * @author Nathan Smith
 */
public class MainLoginPanel extends JXPanel {

    /**
     * Creates new form LoginPanel
     */
    public MainLoginPanel() {

        initComponents();

        usernameTextField.setPrompt("Username");
        usernameTextField.setPromptForeground(Colors.PromptText.color());
        passwordTextField.setPrompt("Password");
        passwordTextField.setPromptForeground(Colors.PromptText.color());

        mattePainter1.setFillPaint(Color.white);
        this.setBackgroundPainter(mattePainter1);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mattePainter1 = new org.jdesktop.swingx.painter.MattePainter();
        usernameTextField = new org.jdesktop.swingx.JXTextField();
        passwordTextField = new org.jdesktop.swingx.JXTextField();
        loginButton = new org.jdesktop.swingx.JXButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();

        mattePainter1.setFillHorizontal(true);
        mattePainter1.setFillPaint(Color.white);
        mattePainter1.setFillVertical(true);

        usernameTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        passwordTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        loginButton.setBackground(Colors.ButtonColorOrange.color());
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginButton.setText("Login");
        loginButton.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainLogo.png"))); // NOI18N
        jXLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXLabel1.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        jXLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/border.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(629, 629, 629)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String applicationId = "15e4295d-3df5-4ae8-9727-b6a821003dd9";   // Identifies your Application
        String applicationName = "RealWorld";   // No spaces for best results (e.g., MyAppName)
        String tokenKeyMoniker = "04b11650-b3bb-41d6-91a6-c19936aaf4e5";
        String sharedSecret = "8a72063be6d0409da86a5c239e39fd10";
        String clientString = "gbtestc";
        String userName = usernameTextField.getText();
        String password = passwordTextField.getText();

        OAuthConfig config = new OAuthConfig();
        config.setApplicationId(applicationId);
        config.setApplicationName(applicationName);  	// Needed only for OAuth 2 Assertion 
        config.setConsumerKey(tokenKeyMoniker);
        config.setConsumerSecret(sharedSecret);        	// Needed only for OAuth 1 & OAuth 2 Assertion 
        config.setClientString(clientString);	      	// Needed only for OAuth 2

        OAuthServiceFactory oauthFactory = new OAuthServiceFactory(config);
        OAuth2PasswordService oauthService = oauthFactory.build(OAuth2PasswordService.class);

        try {
            URL apiUrl = new URL("https://api.learningstudio.com/me");
            OAuth2Request oauthRequest = oauthService.generateOAuth2PasswordRequest(userName, password);
            Map httpHeaders = oauthRequest.getHeaders();
            HttpsURLConnection httpConn = (HttpsURLConnection) apiUrl.openConnection();
            httpConn.setRequestMethod("GET");

            for (Object headerName : httpHeaders.keySet()) {
                httpConn.addRequestProperty((String) headerName, (String) httpHeaders.get(headerName));
            }

            int responseCode = httpConn.getResponseCode();
            if (responseCode == 200) {
                AuthenticationData data = new AuthenticationData(config, oauthFactory, httpHeaders, userName, password);
                MainScreen main = new MainScreen(data);
                JXFrame frame = (JXFrame) SwingXUtilities.getAncestor(JXFrame.class, getParent());
                frame.remove(MainLoginPanel.this);
                frame.revalidate();
                frame.add(main);
                frame.revalidate();
                frame.repaint();
            }
        } catch (RuntimeException rex) {
            throw rex;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Incorrect Username and/or Password");
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXButton loginButton;
    private org.jdesktop.swingx.painter.MattePainter mattePainter1;
    private org.jdesktop.swingx.JXTextField passwordTextField;
    private org.jdesktop.swingx.JXTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
